version: 'runtime-{branch}-build-{build}'
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: x64
before_build:
- cmd: >-
    mkdir build

    cd build

    cmake -G"Visual Studio 15 2017 Win64" -DRUNTIME_BUILD_ASTYLE:bool=true -DRUNTIME_BUILD_GLSLANG:bool=true -DRUNTIME_BUILD_LIBPNG:bool=true -DRUNTIME_BUILD_PROTOBUF:bool=true -DRUNTIME_BUILD_XXD:bool=true -DRUNTIME_BUILD_ZLIB=true -DRUNTIME_BUILD_NODEEDITOR=true -DQt5_DIR:path=C:/Qt/5.9.1/msvc2017_64/lib/cmake/Qt5 -DCMAKE_INSTALL_PREFIX:path=../msvc64-runtime ..
    
    cd ..

    deploy.bat
build:
  project: build/runtime.sln
  verbosity: minimal
after_build:
- cmd: >-
    msbuild build/INSTALL.vcxproj

    7z a msvc64-runtime.zip msvc64-runtime
artifacts:
- path: msvc64-runtime.zip
  name: msvc64-runtime
deploy:
- provider: GitHub
  auth_token:
    secure: EW1TkwxBon7bfGf3JnK6SI3dcH2RLAaXRsLlJ5IJITdbDr1zCHFo6U2KuQEhDIq7
  artifact: msvc64-runtime
  on:
    branch: master
    DEPLOY: YES